<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="en-gb">
	<title type="text">NEWS</title>
	<subtitle type="text">Cpaesmite Consulting - International Commerce And Logistics</subtitle>
	<link rel="alternate" type="text/html" href="https://cpaesmite.github.io"/>
	<id>https://cpaesmite.github.io/index.php</id>
	<updated>2019-09-07T19:39:40Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="https://cpaesmite.github.io/index.php?view=category&amp;id=57%3Anoticias-paraguay&amp;option=com_content&amp;Itemid=58&amp;lang=en&amp;format=feed&amp;type=atom" />
	<entry>
		<title>En Sudamérica, Paraguay es la economía que más avanzó en cuanto a Producto Interno Bruto </title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=524%3Aen-sudamerica-paraguay-es-la-economia-que-mas-avanzo-en-cuanto-a-producto-interno-bruto-&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2017-02-03T17:41:07Z</published>
		<updated>2017-02-03T17:41:07Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=524%3Aen-sudamerica-paraguay-es-la-economia-que-mas-avanzo-en-cuanto-a-producto-interno-bruto-&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p class=&quot;caption&quot;&gt;En Sudamérica, Paraguay es la economía que más avanzó en cuanto a Producto Interno Bruto (PIB) entre el 2012 y el 2016, con una expansión total del 24%, según el informe anual de la Comisión Económica para América Latina y el Caribe (Cepal).&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;El organismo de las Naciones Unidas señala que Panamá lidera el ranking de crecimiento del último quinquenio, mientras Venezuela es el país que más cayó, dentro de América Latina. En tanto, América Latina y el Caribe acumulan una expansión del 5,1%. A Paraguay le siguen Perú y Colombia, con 21% y 18%, respectivamente, mientras que Argentina y Brasil retrocedieron. Es decir, cayeron 0,6% y 2,5% cada uno en los últimos 5 años, de acuerdo al informe anual de Cepal.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Estas caídas, en tres países cuyos PIB son importantes en la región, inciden fuertemente en abatir el indicador del crecimiento de toda la América Latina, de acuerdo a un análisis de Infobae.com. “La importancia de nuevas inversiones de carácter productivo es clave para interpretar, porque algunas naciones crecen, mientras que otras están estancadas o incluso retroceden. El promedio de inversiones como proporción del PBI se ubica en alrededor del 20% en América Latina. Pero en Panamá este indicador se ubica en nada menos que 40%, así que no debe sorprender que este país lidere en estos últimos años el crecimiento”, destaca.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;En el 2016, Brasil registró inversiones por un 17% de su PIB, Argentina 15%, mientras que el menor nivel de inversiones en toda la región le corresponde a Venezuela, donde las inversiones representaron en el 2016 apenas el 4% del PBI del país, de acuerdo a los datos de Cepal.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Por otro lado, en este 2017, Paraguay se enfrentará a un entorno regional y mundial más complejo, en donde solo el precio de los commodities, sumado al factores internos, está “a favor” de la economía. En ese sentido Cepal, en su informe, proyecta un crecimiento de Paraguay de 3,8%, inferior a lo que se tuvo durante el 2016, que fue de (4%).&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Cepal argumenta que el crecimiento del PIB estará sustentado por mayores niveles de inversión pública y privada, y por una positiva pero moderada producción de energía eléctrica.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Fuente: La Nación&lt;/p&gt;</summary>
		<content type="html">&lt;p class=&quot;caption&quot;&gt;En Sudamérica, Paraguay es la economía que más avanzó en cuanto a Producto Interno Bruto (PIB) entre el 2012 y el 2016, con una expansión total del 24%, según el informe anual de la Comisión Económica para América Latina y el Caribe (Cepal).&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;El organismo de las Naciones Unidas señala que Panamá lidera el ranking de crecimiento del último quinquenio, mientras Venezuela es el país que más cayó, dentro de América Latina. En tanto, América Latina y el Caribe acumulan una expansión del 5,1%. A Paraguay le siguen Perú y Colombia, con 21% y 18%, respectivamente, mientras que Argentina y Brasil retrocedieron. Es decir, cayeron 0,6% y 2,5% cada uno en los últimos 5 años, de acuerdo al informe anual de Cepal.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Estas caídas, en tres países cuyos PIB son importantes en la región, inciden fuertemente en abatir el indicador del crecimiento de toda la América Latina, de acuerdo a un análisis de Infobae.com. “La importancia de nuevas inversiones de carácter productivo es clave para interpretar, porque algunas naciones crecen, mientras que otras están estancadas o incluso retroceden. El promedio de inversiones como proporción del PBI se ubica en alrededor del 20% en América Latina. Pero en Panamá este indicador se ubica en nada menos que 40%, así que no debe sorprender que este país lidere en estos últimos años el crecimiento”, destaca.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;En el 2016, Brasil registró inversiones por un 17% de su PIB, Argentina 15%, mientras que el menor nivel de inversiones en toda la región le corresponde a Venezuela, donde las inversiones representaron en el 2016 apenas el 4% del PBI del país, de acuerdo a los datos de Cepal.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Por otro lado, en este 2017, Paraguay se enfrentará a un entorno regional y mundial más complejo, en donde solo el precio de los commodities, sumado al factores internos, está “a favor” de la economía. En ese sentido Cepal, en su informe, proyecta un crecimiento de Paraguay de 3,8%, inferior a lo que se tuvo durante el 2016, que fue de (4%).&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Cepal argumenta que el crecimiento del PIB estará sustentado por mayores niveles de inversión pública y privada, y por una positiva pero moderada producción de energía eléctrica.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;Fuente: La Nación&lt;/p&gt;</content>
	</entry>
	<entry>
		<title> Logística de Calidad</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=448%3A-logistica-de-calidad&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2015-08-22T13:34:01Z</published>
		<updated>2015-08-22T13:34:01Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=448%3A-logistica-de-calidad&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt;En nuestro espacio de Trabajos Técnicos compartimos la presentación realizada por nuestro director el Cr. Federico Esmite en el Evento:&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&amp;nbsp;XI Encuentro de Protagonistas, realizado en el Hotel Bourbon de Asunción, Paraguay el día&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&amp;nbsp;20 de Agosto de 2015.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&lt;img mce_src=&quot;https://cpaesmite.github.io/images/Noticias/esmite3.jpg&quot; src=&quot;https://cpaesmite.github.io/images/Noticias/esmite3.jpg&quot; width=&quot;500&quot; height=&quot;333&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;img mce_src=&quot;https://cpaesmite.github.io/images/banners/captura.jpg&quot; src=&quot;https://cpaesmite.github.io/images/banners/captura.jpg&quot; width=&quot;543&quot; height=&quot;367&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;En nuestro espacio de Trabajos Técnicos compartimos la presentación realizada por nuestro director el Cr. Federico Esmite en el Evento:&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&amp;nbsp;XI Encuentro de Protagonistas, realizado en el Hotel Bourbon de Asunción, Paraguay el día&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&amp;nbsp;20 de Agosto de 2015.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&lt;img mce_src=&quot;https://cpaesmite.github.io/images/Noticias/esmite3.jpg&quot; src=&quot;https://cpaesmite.github.io/images/Noticias/esmite3.jpg&quot; width=&quot;500&quot; height=&quot;333&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;img mce_src=&quot;https://cpaesmite.github.io/images/banners/captura.jpg&quot; src=&quot;https://cpaesmite.github.io/images/banners/captura.jpg&quot; width=&quot;543&quot; height=&quot;367&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Uruguay XXI - Paraguay</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=439%3Auruguay-xxi-paraguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2015-05-23T20:38:07Z</published>
		<updated>2015-05-23T20:38:07Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=439%3Auruguay-xxi-paraguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt;Este informe presenta los principales datos y la situación económica de Paraguay así como también las relaciones bilaterales con Uruguay y las oportunidades de exportaciones hacia dicho destino.&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;Documento completo en:&lt;/p&gt;&lt;p&gt;http://www.uruguayxxi.gub.uy/informacion/wp-content/uploads/sites/9/2015/05/Informe-Paraguay-Set-2014-Uruguay-XXI.pdf&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;Fuente: Uruguay XXI&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;Este informe presenta los principales datos y la situación económica de Paraguay así como también las relaciones bilaterales con Uruguay y las oportunidades de exportaciones hacia dicho destino.&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;Documento completo en:&lt;/p&gt;&lt;p&gt;http://www.uruguayxxi.gub.uy/informacion/wp-content/uploads/sites/9/2015/05/Informe-Paraguay-Set-2014-Uruguay-XXI.pdf&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;Fuente: Uruguay XXI&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>PARAGUAY - TEMAS SELECCIONADOS</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=427%3Aparaguay-temas-seleccionados&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2015-02-27T11:52:30Z</published>
		<updated>2015-02-27T11:52:30Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=427%3Aparaguay-temas-seleccionados&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt;Este documento de temas seleccionados para Paraguay fue preparado por un equipo de&amp;nbsp;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;funcionarios del Fondo Monetario Internacional como documentación de apoyo para la&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;consulta periódica con el país. El documento está basado en información disponible al&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;momento en que fue finalizado el 28 de enero de 2015. Las opiniones expresadas en este&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;documento son las del personal técnico y no reflejan necesariamente las opiniones del&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;gobierno de Paraguay o del Directorio Ejecutivo del FMI.&amp;nbsp;&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;&lt;b&gt;Temas:&lt;/b&gt;&lt;/p&gt;&lt;p&gt;&lt;ul&gt;&lt;li&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;LA IMPORTANCIA DE LOS EFECTOS DE CONTAGIO MUNDIALES Y REGIONALES
PARA PARAGUAY&lt;/span&gt;&lt;/li&gt;&lt;li&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;LA SOSTENIBILIDAD DE LA DEUDA, LA ESTABILIZACIÓN CÍCLICA Y LA LEY DE
RESPONSABILIDAD FISCAL: UN EJERCICIO DE SIMULACIÓN&lt;/span&gt;&lt;/li&gt;&lt;li&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;LA INFORMALIDAD EN PARAGUAY: EVIDENCIA MACRO-MICRO Y EFECTOS
SOBRE LA FORMULACIÓN DE LAS POLÍTICAS&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;Documento completo en:&lt;/p&gt;&lt;p&gt;http://www.imf.org/external/spanish/pubs/ft/scr/2015/cr1538s.pdf?utm_medium=referral&amp;amp;utm_source=pulsenews&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;Este documento de temas seleccionados para Paraguay fue preparado por un equipo de&amp;nbsp;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;funcionarios del Fondo Monetario Internacional como documentación de apoyo para la&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;consulta periódica con el país. El documento está basado en información disponible al&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;momento en que fue finalizado el 28 de enero de 2015. Las opiniones expresadas en este&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;documento son las del personal técnico y no reflejan necesariamente las opiniones del&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;gobierno de Paraguay o del Directorio Ejecutivo del FMI.&amp;nbsp;&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;&lt;b&gt;Temas:&lt;/b&gt;&lt;/p&gt;&lt;p&gt;&lt;ul&gt;&lt;li&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;LA IMPORTANCIA DE LOS EFECTOS DE CONTAGIO MUNDIALES Y REGIONALES
PARA PARAGUAY&lt;/span&gt;&lt;/li&gt;&lt;li&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;LA SOSTENIBILIDAD DE LA DEUDA, LA ESTABILIZACIÓN CÍCLICA Y LA LEY DE
RESPONSABILIDAD FISCAL: UN EJERCICIO DE SIMULACIÓN&lt;/span&gt;&lt;/li&gt;&lt;li&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;LA INFORMALIDAD EN PARAGUAY: EVIDENCIA MACRO-MICRO Y EFECTOS
SOBRE LA FORMULACIÓN DE LAS POLÍTICAS&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p&gt;Documento completo en:&lt;/p&gt;&lt;p&gt;http://www.imf.org/external/spanish/pubs/ft/scr/2015/cr1538s.pdf?utm_medium=referral&amp;amp;utm_source=pulsenews&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Declaración de la misión del FMI al finalizar su visita a Paraguay</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=411%3Adeclaracion-de-la-mision-del-fmi-al-finalizar-su-visita-a-paraguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2014-12-14T14:00:42Z</published>
		<updated>2014-12-14T14:00:42Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=411%3Adeclaracion-de-la-mision-del-fmi-al-finalizar-su-visita-a-paraguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;font-size: 12.222222328186px; line-height: 1.3em;&quot;&gt;12 de diciembre de 2014&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;font-size: 12.222222328186px; line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;font-size: 12.222222328186px; line-height: 1.3em;&quot;&gt;Un equipo integrado por personal técnico del Fondo Monetario Internacional (FMI), dirigido por Andre Meier, visitó Asunción del 1 al 12 de diciembre para mantener conversaciones sobre la Consulta del Artículo IV correspondiente a 2014. El equipo se reunió con el Presidente del Banco Central, Carlos Fernández; el Ministro de Hacienda, Germán Rojas; el Ministro de Trabajo, Empleo y Seguridad Social, Guillermo Sosa; el Ministro de Obras Públicas y Comunicaciones, Ramón Jiménez; otros altos funcionarios, y representantes del Congreso, el sector privado, centros de estudio y la comunidad de donantes. Al concluir la visita, el Sr. Meier emitió la siguiente declaración:&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;“Paraguay sigue siendo una de las economías más dinámicas de América Latina, con un crecimiento proyectado de alrededor de 4% para este año y el próximo. La deuda pública se mantiene en un nivel moderado, las reservas internacionales son abundantes, y se prevé que la inflación permanezca en línea con la meta. A pesar de estos sólidos fundamentos macroeconómicos, las perspectivas están sujetas a riesgos vinculados con precios más bajos de las materias primas agrícolas, debilidades económicas de algunos socios comerciales y shocks relacionados con factores climáticos. Asimismo, Paraguay enfrenta importantes desafíos estructurales, entre ellos, las grandes deficiencias de infraestructura, los malos resultados en materia de educación y los bajos niveles de eficiencia en el sector público.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;“Las autoridades han comenzado a enfrentar algunos de estos importantes desafíos estructurales. La recaudación de impuestos ha mejorado considerablemente; se han iniciado los preparativos para poner en marcha varios proyectos de infraestructura de gran envergadura, y la Ley de Libre Acceso Ciudadano a la Información Pública y Transparencia Gubernamental, adoptada recientemente, fomentará la transparencia del gobierno. Estos esfuerzos merecen pleno apoyo y deberían ampliarse para conseguir mejoras duraderas en los servicios públicos, la calidad institucional y el estado de derecho. Estas mejoras, a su vez, son esenciales para atraer inversiones, mejorar la productividad y apuntalar el crecimiento a mediano plazo, así como para reducir la pobreza.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;</summary>
		<content type="html">&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;font-size: 12.222222328186px; line-height: 1.3em;&quot;&gt;12 de diciembre de 2014&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;font-size: 12.222222328186px; line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;font-size: 12.222222328186px; line-height: 1.3em;&quot;&gt;Un equipo integrado por personal técnico del Fondo Monetario Internacional (FMI), dirigido por Andre Meier, visitó Asunción del 1 al 12 de diciembre para mantener conversaciones sobre la Consulta del Artículo IV correspondiente a 2014. El equipo se reunió con el Presidente del Banco Central, Carlos Fernández; el Ministro de Hacienda, Germán Rojas; el Ministro de Trabajo, Empleo y Seguridad Social, Guillermo Sosa; el Ministro de Obras Públicas y Comunicaciones, Ramón Jiménez; otros altos funcionarios, y representantes del Congreso, el sector privado, centros de estudio y la comunidad de donantes. Al concluir la visita, el Sr. Meier emitió la siguiente declaración:&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;“Paraguay sigue siendo una de las economías más dinámicas de América Latina, con un crecimiento proyectado de alrededor de 4% para este año y el próximo. La deuda pública se mantiene en un nivel moderado, las reservas internacionales son abundantes, y se prevé que la inflación permanezca en línea con la meta. A pesar de estos sólidos fundamentos macroeconómicos, las perspectivas están sujetas a riesgos vinculados con precios más bajos de las materias primas agrícolas, debilidades económicas de algunos socios comerciales y shocks relacionados con factores climáticos. Asimismo, Paraguay enfrenta importantes desafíos estructurales, entre ellos, las grandes deficiencias de infraestructura, los malos resultados en materia de educación y los bajos niveles de eficiencia en el sector público.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;“Las autoridades han comenzado a enfrentar algunos de estos importantes desafíos estructurales. La recaudación de impuestos ha mejorado considerablemente; se han iniciado los preparativos para poner en marcha varios proyectos de infraestructura de gran envergadura, y la Ley de Libre Acceso Ciudadano a la Información Pública y Transparencia Gubernamental, adoptada recientemente, fomentará la transparencia del gobierno. Estos esfuerzos merecen pleno apoyo y deberían ampliarse para conseguir mejoras duraderas en los servicios públicos, la calidad institucional y el estado de derecho. Estas mejoras, a su vez, son esenciales para atraer inversiones, mejorar la productividad y apuntalar el crecimiento a mediano plazo, así como para reducir la pobreza.&lt;/p&gt;&lt;p class=&quot;caption&quot;&gt;</content>
	</entry>
	<entry>
		<title>Doing Business - Paraguay 2014</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=358%3Adoing-business-paraguay-2014&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2014-05-11T14:54:12Z</published>
		<updated>2014-05-11T14:54:12Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=358%3Adoing-business-paraguay-2014&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt;Doing Business sheds light on how easy or difficult it is &lt;span style=&quot;line-height: 1.3em;&quot;&gt;for a local entrepreneur to open and run a small to &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;medium-size business when complying with relevant &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;regulations. It measures and tracks changes in &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;regulations affecting 11 areas in the life cycle of a &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;business: starting a business, dealing with construction &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;permits, getting electricity, registering property, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;getting credit, protecting investors, paying taxes, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;trading across borders, enforcing contracts, resolving &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;insolvency and employing workers.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;In a series of annual reports Doing Business presents &lt;span style=&quot;line-height: 1.3em;&quot;&gt;quantitative indicators on business regulations and the &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;protection of property rights that can be compared &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;across 189 economies, from Afghanistan to Zimbabwe, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;over time. The data set covers 47 economies in SubSaharan Africa, 33 in Latin America and the Caribbean, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;25 in East Asia and the Pacific, 25 in Eastern Europe &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;and Central Asia, 20 in the Middle East and North &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Africa and 8 in South Asia, as well as 31 OECD highincome economies. The indicators are used to analyze &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;economic outcomes and identify what reforms have &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;worked, where and why.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;This economy profile presents the Doing Business &lt;span style=&quot;line-height: 1.3em;&quot;&gt;indicators for Paraguay. To allow useful comparison, it &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;also provides data for other selected economies &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;(comparator economies) for each indicator. The data in &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;this report are current as of June 1, 2013 (except for &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;the paying taxes indicators, which cover the period &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;January–December 2012). &lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
</summary>
		<content type="html">&lt;p&gt;Doing Business sheds light on how easy or difficult it is &lt;span style=&quot;line-height: 1.3em;&quot;&gt;for a local entrepreneur to open and run a small to &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;medium-size business when complying with relevant &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;regulations. It measures and tracks changes in &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;regulations affecting 11 areas in the life cycle of a &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;business: starting a business, dealing with construction &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;permits, getting electricity, registering property, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;getting credit, protecting investors, paying taxes, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;trading across borders, enforcing contracts, resolving &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;insolvency and employing workers.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;In a series of annual reports Doing Business presents &lt;span style=&quot;line-height: 1.3em;&quot;&gt;quantitative indicators on business regulations and the &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;protection of property rights that can be compared &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;across 189 economies, from Afghanistan to Zimbabwe, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;over time. The data set covers 47 economies in SubSaharan Africa, 33 in Latin America and the Caribbean, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;25 in East Asia and the Pacific, 25 in Eastern Europe &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;and Central Asia, 20 in the Middle East and North &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Africa and 8 in South Asia, as well as 31 OECD highincome economies. The indicators are used to analyze &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;economic outcomes and identify what reforms have &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;worked, where and why.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;This economy profile presents the Doing Business &lt;span style=&quot;line-height: 1.3em;&quot;&gt;indicators for Paraguay. To allow useful comparison, it &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;also provides data for other selected economies &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;(comparator economies) for each indicator. The data in &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;this report are current as of June 1, 2013 (except for &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;the paying taxes indicators, which cover the period &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;January–December 2012). &lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
</content>
	</entry>
	<entry>
		<title>Paraguay - Perfil País (Uruguay)</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=354%3Aparaguay-perfil-pais-uruguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2014-04-22T14:56:29Z</published>
		<updated>2014-04-22T14:56:29Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=354%3Aparaguay-perfil-pais-uruguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt;El presente informe exhibe un panorama de la &lt;span style=&quot;line-height: 1.3em;&quot;&gt;actualidad económico-comercial de Paraguay, sus &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;relaciones comerciales con Uruguay y las &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;oportunidades con las que cuentan nuestros &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;productos de ser exportados hacia dicho destino.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;En el mismo hallarán información de los aranceles &lt;span style=&quot;line-height: 1.3em;&quot;&gt;aduaneros aplicados, los canales de distribución, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;principales puntos de entrada y precios de fletes &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;internacionales, así como también la forma correcta &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;para el embalaje y etiquetado de los productos que &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;tienen a Paraguay como su destino final.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Por último &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;se mencionan algunas de las empresas uruguayas &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;con inversiones en Paraguay.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Según estimaciones del Fondo Monetario &lt;span style=&quot;line-height: 1.3em;&quot;&gt;Internacional, el PIB aumentará en un 4,6%. &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Las exportaciones totales de bienes de Paraguay al &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;resto del mundo alcanzaron un valor de US$ 9.432 &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;millones en 2013, mientras que las importaciones &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;alcanzaron un monto superior a los US$ 12.400 &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;millones en el mismo año.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;El comercio bilateral entre Uruguay y Paraguay es &lt;span style=&quot;line-height: 1.3em;&quot;&gt;muy significativo. Dentro del ranking de destinos de &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;exportación de Uruguay ocupó en 2013 el octavo &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;lugar. El valor de las exportaciones en este año &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;ascendió a US$ 156 millones.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;
</summary>
		<content type="html">&lt;p&gt;El presente informe exhibe un panorama de la &lt;span style=&quot;line-height: 1.3em;&quot;&gt;actualidad económico-comercial de Paraguay, sus &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;relaciones comerciales con Uruguay y las &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;oportunidades con las que cuentan nuestros &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;productos de ser exportados hacia dicho destino.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;En el mismo hallarán información de los aranceles &lt;span style=&quot;line-height: 1.3em;&quot;&gt;aduaneros aplicados, los canales de distribución, &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;principales puntos de entrada y precios de fletes &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;internacionales, así como también la forma correcta &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;para el embalaje y etiquetado de los productos que &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;tienen a Paraguay como su destino final.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Por último &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;se mencionan algunas de las empresas uruguayas &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;con inversiones en Paraguay.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Según estimaciones del Fondo Monetario &lt;span style=&quot;line-height: 1.3em;&quot;&gt;Internacional, el PIB aumentará en un 4,6%. &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Las exportaciones totales de bienes de Paraguay al &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;resto del mundo alcanzaron un valor de US$ 9.432 &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;millones en 2013, mientras que las importaciones &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;alcanzaron un monto superior a los US$ 12.400 &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;millones en el mismo año.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;El comercio bilateral entre Uruguay y Paraguay es &lt;span style=&quot;line-height: 1.3em;&quot;&gt;muy significativo. Dentro del ranking de destinos de &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;exportación de Uruguay ocupó en 2013 el octavo &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;lugar. El valor de las exportaciones en este año &lt;/span&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;ascendió a US$ 156 millones.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;
</content>
	</entry>
	<entry>
		<title>PARAGUAY - El dólar se elevó a G. 4.730 ante la expectativa por decisión de EE.UU.</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=330%3Aparaguay-el-dolar-se-elevo-a-g-4730-ante-la-expectativa-por-decision-de-eeuu&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2014-01-30T09:58:33Z</published>
		<updated>2014-01-30T09:58:33Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=330%3Aparaguay-el-dolar-se-elevo-a-g-4730-ante-la-expectativa-por-decision-de-eeuu&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt;El dólar se elevó a G. 4.730 ante la expectativa por decisión de EE.UU.&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;El dólar trepó 30 puntos y se cotizó ayer en promedio a G. 4.730 por unidad, día en que los mercados globales estaban atentos a las decisiones de la Reserva Federal norteamericana. Los directivos del Banco Central del Paraguay (BCP) aseguran que el contexto en EE.UU. es el que sigue generando mayor presión sobre la moneda local, y en menor medida la situación de los vecinos.&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Desde la quincena del mes pasado, ocasión en que la Reserva Federal estadunidense (FED) anunció la disminución de US$ 10.000 millones de los estímulos monetarios, el dólar se encareció cerca de 200 puntos frente a la moneda local, lo que representa una variación del 5%. Si comparamos con el cambio de enero del año pasado, la variación es del 9%, ya que la divisa se cotizaba en promedio a G. 4.350 en ese momento.&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Según Roland Holst, miembro del Directorio de la banca matriz, el contexto en el país norteamericano es el que marca la tendencia de los mercados mundiales, de lo que Paraguay no está exento. Asegura que casi toda la región están experimentando una depreciación de sus monedas.&lt;/p&gt;
&lt;p&gt;
</summary>
		<content type="html">&lt;p&gt;El dólar se elevó a G. 4.730 ante la expectativa por decisión de EE.UU.&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;El dólar trepó 30 puntos y se cotizó ayer en promedio a G. 4.730 por unidad, día en que los mercados globales estaban atentos a las decisiones de la Reserva Federal norteamericana. Los directivos del Banco Central del Paraguay (BCP) aseguran que el contexto en EE.UU. es el que sigue generando mayor presión sobre la moneda local, y en menor medida la situación de los vecinos.&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Desde la quincena del mes pasado, ocasión en que la Reserva Federal estadunidense (FED) anunció la disminución de US$ 10.000 millones de los estímulos monetarios, el dólar se encareció cerca de 200 puntos frente a la moneda local, lo que representa una variación del 5%. Si comparamos con el cambio de enero del año pasado, la variación es del 9%, ya que la divisa se cotizaba en promedio a G. 4.350 en ese momento.&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Según Roland Holst, miembro del Directorio de la banca matriz, el contexto en el país norteamericano es el que marca la tendencia de los mercados mundiales, de lo que Paraguay no está exento. Asegura que casi toda la región están experimentando una depreciación de sus monedas.&lt;/p&gt;
&lt;p&gt;
</content>
	</entry>
	<entry>
		<title>Misión del FMI concluye visita al Paraguay</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=319%3Amision-del-fmi-concluye-visita-al-paraguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2013-12-31T11:37:26Z</published>
		<updated>2013-12-31T11:37:26Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=319%3Amision-del-fmi-concluye-visita-al-paraguay&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Comunicado de Prensa No. 13/502&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;12 de diciembre 2013&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;Una misión del Fondo Monetario Internacional (FMI) visitó Paraguay del 2 al 12 de diciembre del 2013 para dialogar con funcionarios del gobierno, donantes, y el sector privado como parte de las consultas anuales del Artículo IV del FMI realizadas con sus países miembros. Al concluir la visita, el jefe de la misión, Ugo Fasano, emitió la siguiente declaración hoy en Asunción:&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;“Los fundamentos económicos del Paraguay son fuertes—el nivel de deuda es bajo, las reservas oficiales son considerables y el déficit fiscal es manejable. El principal desafío que enfrenta el país es mejorar el desarrollo social y económico, que ha quedado rezagado con relación a la región, en medio de debilidades estructurales e institucionales generalizadas.&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;“La perspectiva del Paraguay para el 2014 es positiva. El crecimiento debería permanecer fuerte en 4,8 por ciento, la inflación anual posiblemente aumentaría de actualmente 4,4 por ciento a la meta de inflación del Banco Central del Paraguay de 5,0 por ciento, y los déficits fiscales y de cuenta corriente estarían en niveles bajos. Existen, sin embargo, riesgos. Los principales riesgos a la baja surgen de posibles efectos derivados de un crecimiento regional más débil y de condiciones financieras globales más restrictivas, mientras que un progreso más acelerado en la implementación de la reforma del gobierno representa un riesgo a la alza. Además, si bien el sector bancario sigue sólido, éste ameritaría un monitoreo más cercano si aumenta el crecimiento del crédito.&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
</summary>
		<content type="html">&lt;p class=&quot;caption&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Comunicado de Prensa No. 13/502&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;12 de diciembre 2013&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;Una misión del Fondo Monetario Internacional (FMI) visitó Paraguay del 2 al 12 de diciembre del 2013 para dialogar con funcionarios del gobierno, donantes, y el sector privado como parte de las consultas anuales del Artículo IV del FMI realizadas con sus países miembros. Al concluir la visita, el jefe de la misión, Ugo Fasano, emitió la siguiente declaración hoy en Asunción:&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;“Los fundamentos económicos del Paraguay son fuertes—el nivel de deuda es bajo, las reservas oficiales son considerables y el déficit fiscal es manejable. El principal desafío que enfrenta el país es mejorar el desarrollo social y económico, que ha quedado rezagado con relación a la región, en medio de debilidades estructurales e institucionales generalizadas.&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt;“La perspectiva del Paraguay para el 2014 es positiva. El crecimiento debería permanecer fuerte en 4,8 por ciento, la inflación anual posiblemente aumentaría de actualmente 4,4 por ciento a la meta de inflación del Banco Central del Paraguay de 5,0 por ciento, y los déficits fiscales y de cuenta corriente estarían en niveles bajos. Existen, sin embargo, riesgos. Los principales riesgos a la baja surgen de posibles efectos derivados de un crecimiento regional más débil y de condiciones financieras globales más restrictivas, mientras que un progreso más acelerado en la implementación de la reforma del gobierno representa un riesgo a la alza. Además, si bien el sector bancario sigue sólido, éste ameritaría un monitoreo más cercano si aumenta el crecimiento del crédito.&lt;/p&gt;
&lt;p class=&quot;caption&quot;&gt; &lt;/p&gt;
</content>
	</entry>
	<entry>
		<title>PARAGUAY - TRABAJO DECENTE Y DESARROLLO HUMANO: DOS VÍAS PARA MEJORAR LA VIDA DE LAS PERSONAS</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=301%3Atrabajo-decente-y-desarrollo-humano-dos-vias-para-mejorar-la-vida-de-las-personas&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en"/>
		<published>2013-10-23T11:16:08Z</published>
		<updated>2013-10-23T11:16:08Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=301%3Atrabajo-decente-y-desarrollo-humano-dos-vias-para-mejorar-la-vida-de-las-personas&amp;catid=57%3Anoticias-paraguay&amp;Itemid=58&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Este informe analiza el desarrollo de las personas en Paraguay vinculando dos paradigmas: Desarrollo Humano (DH) y Trabajo Decente (TD), empleados por el PNUD y la OIT, respectivamente.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;El enfoque de DH sostiene que las políticas sociales y económicas deben ampliar las capacidades individuales y la libertad de las personas para lograr una vida mejor. En consecuencia, una prueba esencial del desarrollo, que incluye la reducción de pobreza es si, de facto, la gente ha logrado mayores libertades. El DH se fundamenta en dos elementos básicos:&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;a) la formación de capacidades humanas, tales como mejor salud y mejores conocimientos y habilidades, y b) el uso de las capacidades adquiridas, por las personas, para actividades productivas, el ocio y/o la participación en actividades sociales, culturales o políticas.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;De acuerdo a esta definición de Desarrollo Humano, el ingreso económico es sólo una de las dimensiones que genera y define el bienestar. Con frecuencia es instrumental para acceder a capacidades y ejercer libertades, pero no es, por sí solo, el fin del proceso de desarrollo.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;Este enfoque de Desarrollo Humano permite pasar de un concepto de crecimiento de la economía de un país, medido por el Producto Interno Bruto per cápita, al concepto de desarrollo de la gente, vinculado a libertades y capacidades que incluyen el bienestar. Es pasar de la economía a la gente.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;El concepto del Trabajo Decente (TD) está fuertemente asociado con el DH a través de la expansión de las libertades reales de las personas o actores colectivos. La OIT define el Trabajo Decente como el trabajo productivo para los hombres y las mujeres en condiciones de libertad, equidad, seguridad y dignidad humana. Es decir, el Trabajo Decente supone una actividad productiva que aporte un ingreso justo, seguridad en el lugar de trabajo y protección social para las y los trabajadores y sus familias, que ofrezca mejores perspectivas de desarrollo personal y favorezca la integración social; que dé libertad a las personas para manifestar sus inquietudes, organizarse y participar en las decisiones que inciden en su vida; y que garantice la igualdad de oportunidades y de trato para todos. Los objetivos del TD deben existir para todos las y los trabajadores, en la economía formal e informal, en el empleo asalariado o trabajando por cuenta propia, en el campo, en la fábrica, y finalmente en su hogar o en la comunidad.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
</summary>
		<content type="html">&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;Este informe analiza el desarrollo de las personas en Paraguay vinculando dos paradigmas: Desarrollo Humano (DH) y Trabajo Decente (TD), empleados por el PNUD y la OIT, respectivamente.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;El enfoque de DH sostiene que las políticas sociales y económicas deben ampliar las capacidades individuales y la libertad de las personas para lograr una vida mejor. En consecuencia, una prueba esencial del desarrollo, que incluye la reducción de pobreza es si, de facto, la gente ha logrado mayores libertades. El DH se fundamenta en dos elementos básicos:&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;a) la formación de capacidades humanas, tales como mejor salud y mejores conocimientos y habilidades, y b) el uso de las capacidades adquiridas, por las personas, para actividades productivas, el ocio y/o la participación en actividades sociales, culturales o políticas.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;De acuerdo a esta definición de Desarrollo Humano, el ingreso económico es sólo una de las dimensiones que genera y define el bienestar. Con frecuencia es instrumental para acceder a capacidades y ejercer libertades, pero no es, por sí solo, el fin del proceso de desarrollo.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;Este enfoque de Desarrollo Humano permite pasar de un concepto de crecimiento de la economía de un país, medido por el Producto Interno Bruto per cápita, al concepto de desarrollo de la gente, vinculado a libertades y capacidades que incluyen el bienestar. Es pasar de la economía a la gente.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;El concepto del Trabajo Decente (TD) está fuertemente asociado con el DH a través de la expansión de las libertades reales de las personas o actores colectivos. La OIT define el Trabajo Decente como el trabajo productivo para los hombres y las mujeres en condiciones de libertad, equidad, seguridad y dignidad humana. Es decir, el Trabajo Decente supone una actividad productiva que aporte un ingreso justo, seguridad en el lugar de trabajo y protección social para las y los trabajadores y sus familias, que ofrezca mejores perspectivas de desarrollo personal y favorezca la integración social; que dé libertad a las personas para manifestar sus inquietudes, organizarse y participar en las decisiones que inciden en su vida; y que garantice la igualdad de oportunidades y de trato para todos. Los objetivos del TD deben existir para todos las y los trabajadores, en la economía formal e informal, en el empleo asalariado o trabajando por cuenta propia, en el campo, en la fábrica, y finalmente en su hogar o en la comunidad.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt; &lt;/p&gt;
</content>
	</entry>
</feed>
