<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="es-es">
	<title type="text">Inicio</title>
	<subtitle type="text">Cpaesmite Consulting - International Commerce And Logistics</subtitle>
	<link rel="alternate" type="text/html" href="http://cpaesmite.com"/>
	<id>http://cpaesmite.com/index.php</id>
	<updated>2019-09-07T19:29:26Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="http://cpaesmite.com/index.php?option=com_content&amp;view=frontpage&amp;Itemid=1&amp;lang=es&amp;format=feed&amp;type=atom" />
	<entry>
		<title>Inicio </title>
		<link rel="alternate" type="text/html" href="http://cpaesmite.com/index.php?option=com_content&amp;view=article&amp;id=51%3Ainicio-a&amp;Itemid=1&amp;lang=es"/>
		<published>2011-04-28T02:24:02Z</published>
		<updated>2011-04-28T02:24:02Z</updated>
		<id>http://cpaesmite.com/index.php?option=com_content&amp;view=article&amp;id=51%3Ainicio-a&amp;Itemid=1&amp;lang=es</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;/h3&gt;
&lt;p style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;font-weight: bold;&quot; mce_style=&quot;font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Visión&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot; mce_style=&quot;line-height: 1.3em;&quot;&gt;Ser socios estratégicos de organizaciones y empresarios que vean en nuestra asesoría y consultoría profesional un medio para el logro de sus objetivos.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #333333; font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot; mce_style=&quot;color: #333333; font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot;&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Misión&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;/span&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: center;&quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: center;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;Apoyar a organizaciones en áreas claves de su gestión, para que estas logren desarrollar sus negocios y maximizar beneficios; brindando soluciones específicas acorde a las necesidades de nuestros clientes y de acuerdo a estándares de calidad internacionales.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;font-weight: bold;&quot; mce_style=&quot;font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Valores&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;Ética, compromiso y honestidad son la guía de nuestro camino. Buscamos la excelencia en lo que hacemos, basándonos para ello en la capacitación y mejora continua. Tenemos una clara orientación al cliente y los resultados, siendo la proactividad, creatividad, iniciativa, y dinamismo, herramientas claves para el logro de nuestra visión.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;La familia y la pasión por lo que hacemos nos motivan a superarnos cada día.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; line-height: normal;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span class=&quot;caption&quot;&gt;Una inversión&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;color: #000000;&quot; mce_style=&quot;color: #000000;&quot;&gt;Los recursos aplicados en nuestro asesoramiento y horas de consultoría &lt;span style=&quot;mso-spacerun: yes;&quot; mce_style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;constituyen una inversión para la empresa, la cual se debería más que autofinanciar con las eficiencias a lograr. El retorno de la misma se asocia, entre otros, a los siguientes resultados:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;color: #000000;&quot; mce_style=&quot;color: #000000;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;br /&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Incremento del tiempo que el      empresario posee para el desarrollo de su negocio.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Identificación de posibles      situaciones problemáticas y sus soluciones. &lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Capacitación de la dirección y mandos      medios.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Tener información necesaria para      emprender nuevos proyectos.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Maximización de resultados y      reducción del riesgo.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;En general lograr una rentabilidad y      liquidez necesaria que le permita a la empresa trascender en el tiempo.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;&lt;div style=&quot;text-align: justify;&quot; mce_style=&quot;text-align: justify;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;img mce_src=&quot;http://cpaesmite.com/images/banners/positivo%202015%20transparente.bmp&quot; src=&quot;https://cpaesmite.github.io/images/banners/positivo%202015%20transparente.bmp&quot; width=&quot;143&quot; height=&quot;145&quot; style=&quot;font-size: 12.1599998474121px; line-height: 15.8079996109009px; text-align: right;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 15.8079996109009px; text-align: right;&quot;&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;/h3&gt;
&lt;p style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;font-weight: bold;&quot; mce_style=&quot;font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Visión&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;span style=&quot;line-height: 1.3em;&quot; mce_style=&quot;line-height: 1.3em;&quot;&gt;Ser socios estratégicos de organizaciones y empresarios que vean en nuestra asesoría y consultoría profesional un medio para el logro de sus objetivos.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #333333; font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot; mce_style=&quot;color: #333333; font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot;&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Misión&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;/span&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: center;&quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: center;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;Apoyar a organizaciones en áreas claves de su gestión, para que estas logren desarrollar sus negocios y maximizar beneficios; brindando soluciones específicas acorde a las necesidades de nuestros clientes y de acuerdo a estándares de calidad internacionales.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;font-weight: bold;&quot; mce_style=&quot;font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Valores&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;Ética, compromiso y honestidad son la guía de nuestro camino. Buscamos la excelencia en lo que hacemos, basándonos para ello en la capacitación y mejora continua. Tenemos una clara orientación al cliente y los resultados, siendo la proactividad, creatividad, iniciativa, y dinamismo, herramientas claves para el logro de nuestra visión.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;La familia y la pasión por lo que hacemos nos motivan a superarnos cada día.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt;&quot; mce_style=&quot;margin-bottom: .0001pt;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; line-height: normal;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;span style=&quot;color: #135cae; font-weight: bold;&quot; mce_style=&quot;color: #135cae; font-weight: bold;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot; mce_style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span class=&quot;caption&quot;&gt;Una inversión&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/h3&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;color: #000000;&quot; mce_style=&quot;color: #000000;&quot;&gt;Los recursos aplicados en nuestro asesoramiento y horas de consultoría &lt;span style=&quot;mso-spacerun: yes;&quot; mce_style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;constituyen una inversión para la empresa, la cual se debería más que autofinanciar con las eficiencias a lograr. El retorno de la misma se asocia, entre otros, a los siguientes resultados:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;color: #000000;&quot; mce_style=&quot;color: #000000;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot; mce_style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;color: black; mso-ansi-language: ES;&quot; mce_style=&quot;color: black; mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;br /&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Incremento del tiempo que el      empresario posee para el desarrollo de su negocio.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Identificación de posibles      situaciones problemáticas y sus soluciones. &lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Capacitación de la dirección y mandos      medios.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Tener información necesaria para      emprender nuevos proyectos.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Maximización de resultados y      reducción del riesgo.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; mce_style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot; mce_style=&quot;color: black; margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; mce_style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;En general lograr una rentabilidad y      liquidez necesaria que le permita a la empresa trascender en el tiempo.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;&lt;div style=&quot;text-align: justify;&quot; mce_style=&quot;text-align: justify;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;img mce_src=&quot;http://cpaesmite.com/images/banners/positivo%202015%20transparente.bmp&quot; src=&quot;https://cpaesmite.github.io/images/banners/positivo%202015%20transparente.bmp&quot; width=&quot;143&quot; height=&quot;145&quot; style=&quot;font-size: 12.1599998474121px; line-height: 15.8079996109009px; text-align: right;&quot; mce_style=&quot;font-size: 12.1599998474121px; line-height: 15.8079996109009px; text-align: right;&quot;&gt;&lt;/div&gt;</content>
	</entry>
</feed>
