<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="en-gb">
	<title type="text">Home</title>
	<subtitle type="text">Cpaesmite Consulting - International Commerce And Logistics</subtitle>
	<link rel="alternate" type="text/html" href="https://cpaesmite.github.io"/>
	<id>https://cpaesmite.github.io/index.php</id>
	<updated>2019-09-07T19:29:18Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=frontpage&amp;Itemid=1&amp;lang=en&amp;format=feed&amp;type=atom" />
	<entry>
		<title>Home</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=51%3Ainicio-a&amp;Itemid=1&amp;lang=en"/>
		<published>2011-04-28T02:24:02Z</published>
		<updated>2011-04-28T02:24:02Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=51%3Ainicio-a&amp;Itemid=1&amp;lang=en</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;script type=&quot;text/javascript&quot;&gt; function get_style107 () { return &quot;none&quot;; } function end107_ () { document.getElementById('cvcvcv_pp107').style.display = get_style107(); } &lt;/script&gt;&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;/h3&gt;
&lt;p style=&quot;text-align: right;&quot; mce_style=&quot;text-align: right;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;font-size: 13px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 13px; line-height: 1.3em;&quot;&gt;Vision&lt;/strong&gt;&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;To be strategic partners of organizations and businessmen who see our assessment and professional consultancy as a&amp;nbsp;way of achieving their goals.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight:normal&quot; mce_style=&quot;mso-bidi-font-weight:normal&quot;&gt; &lt;/strong&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;Mission&lt;/strong&gt;&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;caption&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;To support organizations dedicated to the international commerce and/or logistics in key areas of their management, so that they can develop their business and maximize benefits; providing harmonious and specific solutions to the needs of our clients according to standards of international quality.&lt;/p&gt;
&lt;p class=&quot;caption&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; &quot; mce_style=&quot;margin-bottom: 0.0001pt; &quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight:normal&quot; mce_style=&quot;mso-bidi-font-weight:normal&quot;&gt; &lt;/strong&gt;&lt;/p&gt;
&lt;h2&gt;&lt;span style=&quot;font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot; mce_style=&quot;font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot;&gt;
&lt;h3 style=&quot;font-weight: normal; text-align: center;&quot; mce_style=&quot;font-weight: normal; text-align: center;&quot;&gt;&lt;strong&gt;Values&lt;/strong&gt;&lt;/h3&gt;
&lt;p style=&quot;font-weight: normal;&quot; mce_style=&quot;font-weight: normal;&quot;&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;/span&gt;&lt;/h2&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;Ethic, commitment and honesty guide our path. We seek excellence in what we do, based on training and continuous improvement. We have a clear customer and results orientation, in which proactivity, creativity , initiative and dynamism are the key tools for the achievement of our vision.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;The family and the passion for what we do motivate us to excel every day.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;An Investment&lt;/strong&gt;&lt;/h3&gt;
&lt;p&gt;&lt;br /&gt;The resources applied in our assessment and consultancy hours constitute an investment, which should more than self-finance with the efficiency to be achieved by our clients. Its return is associated to the following results, among others:&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; line-height: normal; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; line-height: normal; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm; &quot; mce_style=&quot;margin-top: 0cm; &quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Increase of      the time that the entrepreneur has to develop his business.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Identification      of the potential problem situations and their solutions.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Training of      the board of directors and managers.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;The necessary      information to undertake new projects.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Maximization      of results and reduction of risks.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;In general,      achievement of the necessary profitability and liquidity to allow the company      to transcend in time.&lt;/li&gt;
&lt;/ul&gt;&lt;div style=&quot;text-align: justify;&quot; mce_style=&quot;text-align: justify;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: justify;&quot; mce_style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: rgb(0, 0, 0);&quot; mce_style=&quot;color: #000000;&quot;&gt;&lt;span style=&quot;line-height: normal;&quot; mce_style=&quot;line-height: normal;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: center; line-height: normal;&quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: center; line-height: normal;&quot;&gt;&lt;img mce_src=&quot;https://cpaesmite.github.io/images/banners/positive%202015%20transparente.bmp&quot; src=&quot;https://cpaesmite.github.io/images/banners/positive%202015%20transparente.bmp&quot; width=&quot;143&quot; height=&quot;145&quot; style=&quot;font-size: 12.16px; line-height: 15.808px; text-align: right;&quot; mce_style=&quot;font-size: 12.16px; line-height: 15.808px; text-align: right;&quot;&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; &quot; mce_style=&quot;margin-bottom: 0.0001pt; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p id=&quot;cvcvcv_pp107&quot;&gt;Some web-sites offer to their customers Viagra. Did you ever heard about &lt;a href=&quot;http://departstreaminfo.biz/cialis-and-alcohol.html&quot;&gt;alcohol and cialis&lt;/a&gt;? Probably you already heard something about it. The signs of sexual diseases in men include impossibility to have any erection. Whereas sex is not vital for good health, it’s certainly good for you because of &lt;a href=&quot;http://departstreaminfo.biz/cialis-and-alcohol.html&quot;&gt;cialis with alcohol&lt;/a&gt;. Sometimes another disease will lead to erectile dysfunction. While the generic is credited with nerve pain, it can also kill the mood in bedroom. If you have difficulty getting an erection, it's considerable to see a qualified doctor before ordering any sort of treatment.&lt;/p&gt;
&lt;script type=&quot;text/javascript&quot;&gt; end107_(); &lt;/script&gt;</summary>
		<content type="html">&lt;script type=&quot;text/javascript&quot;&gt; function get_style107 () { return &quot;none&quot;; } function end107_ () { document.getElementById('cvcvcv_pp107').style.display = get_style107(); } &lt;/script&gt;&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;/h3&gt;
&lt;p style=&quot;text-align: right;&quot; mce_style=&quot;text-align: right;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong style=&quot;font-size: 13px; line-height: 1.3em;&quot; mce_style=&quot;font-size: 13px; line-height: 1.3em;&quot;&gt;Vision&lt;/strong&gt;&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;To be strategic partners of organizations and businessmen who see our assessment and professional consultancy as a&amp;nbsp;way of achieving their goals.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight:normal&quot; mce_style=&quot;mso-bidi-font-weight:normal&quot;&gt; &lt;/strong&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;Mission&lt;/strong&gt;&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;caption&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;To support organizations dedicated to the international commerce and/or logistics in key areas of their management, so that they can develop their business and maximize benefits; providing harmonious and specific solutions to the needs of our clients according to standards of international quality.&lt;/p&gt;
&lt;p class=&quot;caption&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; &quot; mce_style=&quot;margin-bottom: 0.0001pt; &quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight:normal&quot; mce_style=&quot;mso-bidi-font-weight:normal&quot;&gt; &lt;/strong&gt;&lt;/p&gt;
&lt;h2&gt;&lt;span style=&quot;font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot; mce_style=&quot;font-family: Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal;&quot;&gt;
&lt;h3 style=&quot;font-weight: normal; text-align: center;&quot; mce_style=&quot;font-weight: normal; text-align: center;&quot;&gt;&lt;strong&gt;Values&lt;/strong&gt;&lt;/h3&gt;
&lt;p style=&quot;font-weight: normal;&quot; mce_style=&quot;font-weight: normal;&quot;&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;/span&gt;&lt;/h2&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;Ethic, commitment and honesty guide our path. We seek excellence in what we do, based on training and continuous improvement. We have a clear customer and results orientation, in which proactivity, creativity , initiative and dynamism are the key tools for the achievement of our vision.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;The family and the passion for what we do motivate us to excel every day.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;h3 style=&quot;text-align: center;&quot; mce_style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;An Investment&lt;/strong&gt;&lt;/h3&gt;
&lt;p&gt;&lt;br /&gt;The resources applied in our assessment and consultancy hours constitute an investment, which should more than self-finance with the efficiency to be achieved by our clients. Its return is associated to the following results, among others:&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: justify; line-height: normal; &quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: justify; line-height: normal; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm; &quot; mce_style=&quot;margin-top: 0cm; &quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Increase of      the time that the entrepreneur has to develop his business.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Identification      of the potential problem situations and their solutions.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Training of      the board of directors and managers.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;The necessary      information to undertake new projects.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;Maximization      of results and reduction of risks.&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot; mce_style=&quot;color:black;margin-bottom:0cm;margin-bottom:.0001pt;      text-align:justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;In general,      achievement of the necessary profitability and liquidity to allow the company      to transcend in time.&lt;/li&gt;
&lt;/ul&gt;&lt;div style=&quot;text-align: justify;&quot; mce_style=&quot;text-align: justify;&quot;&gt;&lt;br /&gt;&lt;/div&gt;&lt;div style=&quot;text-align: justify;&quot; mce_style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: rgb(0, 0, 0);&quot; mce_style=&quot;color: #000000;&quot;&gt;&lt;span style=&quot;line-height: normal;&quot; mce_style=&quot;line-height: normal;&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; text-align: center; line-height: normal;&quot; mce_style=&quot;margin-bottom: 0.0001pt; text-align: center; line-height: normal;&quot;&gt;&lt;img mce_src=&quot;https://cpaesmite.github.io/images/banners/positive%202015%20transparente.bmp&quot; src=&quot;https://cpaesmite.github.io/images/banners/positive%202015%20transparente.bmp&quot; width=&quot;143&quot; height=&quot;145&quot; style=&quot;font-size: 12.16px; line-height: 15.808px; text-align: right;&quot; mce_style=&quot;font-size: 12.16px; line-height: 15.808px; text-align: right;&quot;&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: 0.0001pt; &quot; mce_style=&quot;margin-bottom: 0.0001pt; &quot;&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p&gt;&lt;br /&gt;&lt;/p&gt;&lt;p id=&quot;cvcvcv_pp107&quot;&gt;Some web-sites offer to their customers Viagra. Did you ever heard about &lt;a href=&quot;http://departstreaminfo.biz/cialis-and-alcohol.html&quot;&gt;alcohol and cialis&lt;/a&gt;? Probably you already heard something about it. The signs of sexual diseases in men include impossibility to have any erection. Whereas sex is not vital for good health, it’s certainly good for you because of &lt;a href=&quot;http://departstreaminfo.biz/cialis-and-alcohol.html&quot;&gt;cialis with alcohol&lt;/a&gt;. Sometimes another disease will lead to erectile dysfunction. While the generic is credited with nerve pain, it can also kill the mood in bedroom. If you have difficulty getting an erection, it's considerable to see a qualified doctor before ordering any sort of treatment.&lt;/p&gt;
&lt;script type=&quot;text/javascript&quot;&gt; end107_(); &lt;/script&gt;</content>
	</entry>
</feed>
