<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="es-es">
	<title type="text">NUESTROS SERVICIOS</title>
	<subtitle type="text">Cpaesmite Consulting - International Commerce And Logistics</subtitle>
	<link rel="alternate" type="text/html" href="https://cpaesmite.github.io"/>
	<id>https://cpaesmite.github.io/index.php</id>
	<updated>2019-09-07T19:31:30Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=category&amp;id=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es&amp;format=feed&amp;type=atom" />
	<entry>
		<title>Apoyo a empresas extranjeras en Uruguay y Paraguay</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=46%3Aapoyo-a-empresas-extranjeras-en-uruguay-y-paraguay&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es"/>
		<published>2011-04-28T00:21:06Z</published>
		<updated>2011-04-28T00:21:06Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=46%3Aapoyo-a-empresas-extranjeras-en-uruguay-y-paraguay&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Sabemos que el ingreso a una región, a un nuevo país, es un desafío para las empresas. Para minimizar riesgos, adaptarse sin sobrecostos&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;a la idiosincrasia del país y lograr una rápida inserción en el mercado, es fundamental contar con apoyo local. Basándonos en este precepto,&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;brindamos a las empresas nuestro apoyo en las siguientes áreas:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Radicación de inversiones &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Control de gestión y reportes al exterior &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Auditoría financiera y de gestión&lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Gestión temporal de empresas&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;hr /&gt;
&lt;p&gt; &lt;/p&gt;</summary>
		<content type="html">&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Sabemos que el ingreso a una región, a un nuevo país, es un desafío para las empresas. Para minimizar riesgos, adaptarse sin sobrecostos&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;a la idiosincrasia del país y lograr una rápida inserción en el mercado, es fundamental contar con apoyo local. Basándonos en este precepto,&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;brindamos a las empresas nuestro apoyo en las siguientes áreas:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Radicación de inversiones &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Control de gestión y reportes al exterior &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Auditoría financiera y de gestión&lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Gestión temporal de empresas&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;hr /&gt;
&lt;p&gt; &lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Reingeniería de procesos</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=47%3Areingenieria-de-procesos&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es"/>
		<published>2011-04-28T00:26:19Z</published>
		<updated>2011-04-28T00:26:19Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=47%3Areingenieria-de-procesos&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Actualmente lo único constante es el cambio, las empresas crecen, evoluciona la economía y los mercados, el comercio internacional es cada vez más dinámico y consecuentemente la logística asociada a&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;él también lo es.&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;Las empresas deben necesariamente&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;adaptarse, evolucionando junto al entorno que los rodea so pena de quedar en el camino.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt;En este contexto, acompañamos a las empresas en su evolución, focalizando nuestro aporte&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;en el diseño,&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;adaptación y desarrollo de los distintos procesos que conforman su actividad. &lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;Abordamos desde los procesos administrativos, pasando por las comerciales y operativos, hasta los de dirección, apuntando siempre al trabajo en equipo.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt; &lt;/p&gt;
&lt;hr /&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;</summary>
		<content type="html">&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Actualmente lo único constante es el cambio, las empresas crecen, evoluciona la economía y los mercados, el comercio internacional es cada vez más dinámico y consecuentemente la logística asociada a&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;él también lo es.&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;Las empresas deben necesariamente&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;adaptarse, evolucionando junto al entorno que los rodea so pena de quedar en el camino.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt;En este contexto, acompañamos a las empresas en su evolución, focalizando nuestro aporte&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;en el diseño,&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;adaptación y desarrollo de los distintos procesos que conforman su actividad. &lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;Abordamos desde los procesos administrativos, pasando por las comerciales y operativos, hasta los de dirección, apuntando siempre al trabajo en equipo.&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt; &lt;/p&gt;
&lt;hr /&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Planificación, análisis y control de gestión económico-financiera</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=48%3Aplanificacion-analisis-y-control-de-gestion-economico-financiera&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es"/>
		<published>2011-04-28T00:28:00Z</published>
		<updated>2011-04-28T00:28:00Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=48%3Aplanificacion-analisis-y-control-de-gestion-economico-financiera&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt; &lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: normal;&quot;&gt;En la actualidad, contar con un sistema de trabajo que permita una correcta gestión económico-financiera es vital para cualquier tipo de empresa, independientemente de su tamaño, su competitividad, continuidad y desarrollo dependerá de&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;ello.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;En tal sentido, apoyamos &lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;y desarrollamos procesos de planificación, análisis y control de gestión económico-financiera de empresas, basados en sistemas de información sólidos y acorde a las necesidades de las mismas. &lt;/span&gt;&lt;span style=&quot;mso-fareast-font-family: &quot; lang=&quot;ES&quot;&gt;La propuesta específica consiste en trabajar conjuntamente con la empresa en todas o alguna de las siguientes áreas:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Diseño e implementación del sistema de      información (basado en información contable y extracontable)&lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Análisis económico-financiero &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Planificación económico-financiera &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Control de gestión&lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Dirección económico-financiera&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;
&lt;hr /&gt;
&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt; &lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: normal;&quot;&gt;En la actualidad, contar con un sistema de trabajo que permita una correcta gestión económico-financiera es vital para cualquier tipo de empresa, independientemente de su tamaño, su competitividad, continuidad y desarrollo dependerá de&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;ello.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;En tal sentido, apoyamos &lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;y desarrollamos procesos de planificación, análisis y control de gestión económico-financiera de empresas, basados en sistemas de información sólidos y acorde a las necesidades de las mismas. &lt;/span&gt;&lt;span style=&quot;mso-fareast-font-family: &quot; lang=&quot;ES&quot;&gt;La propuesta específica consiste en trabajar conjuntamente con la empresa en todas o alguna de las siguientes áreas:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;ul style=&quot;margin-top: 0cm;&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Diseño e implementación del sistema de      información (basado en información contable y extracontable)&lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Análisis económico-financiero &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Planificación económico-financiera &lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Control de gestión&lt;/span&gt;&lt;/li&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom: .0001pt; text-align: justify; line-height: normal; mso-list: l0 level1 lfo1;&quot;&gt;&lt;span style=&quot;mso-ansi-language: ES;&quot; lang=&quot;ES&quot;&gt;Dirección económico-financiera&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;
&lt;hr /&gt;
&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Planificación y análisis de nuevos proyectos empresariales</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=49%3Aplanificacion-y-analisis-de-nuevos-proyectos-empresariales&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es"/>
		<published>2011-04-28T00:35:42Z</published>
		<updated>2011-04-28T00:35:42Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=49%3Aplanificacion-y-analisis-de-nuevos-proyectos-empresariales&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt; &lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: normal;&quot;&gt;Cada nuevo emprendimiento implica riesgos y oportunidades potenciales. &lt;/span&gt;&lt;span style=&quot;line-height: normal;&quot;&gt;Ponemos a disposición de las empresas herramientas que permiten reducir dichos riesgos y maximizar las oportunidades, entre otras:&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;ul style=&quot;margin-top:0cm&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom:0cm;margin-bottom:.0001pt;text-align:      justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;&lt;span style=&quot;mso-ansi-language:ES&quot; lang=&quot;ES&quot;&gt;Elaboración de planes de negocios &lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top:0cm&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom:0cm;margin-bottom:.0001pt;text-align:      justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;&lt;span style=&quot;mso-ansi-language:ES&quot; lang=&quot;ES&quot;&gt;Realización de estudios de factibilidad      (económico-financiera)&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top:0cm&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom:0cm;margin-bottom:.0001pt;text-align:      justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;&lt;span style=&quot;mso-ansi-language:ES&quot; lang=&quot;ES&quot;&gt;Due&lt;span style=&quot;mso-spacerun:yes&quot;&gt; &lt;/span&gt;diligence&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;hr /&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;</summary>
		<content type="html">&lt;p&gt; &lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;line-height: normal;&quot;&gt;Cada nuevo emprendimiento implica riesgos y oportunidades potenciales. &lt;/span&gt;&lt;span style=&quot;line-height: normal;&quot;&gt;Ponemos a disposición de las empresas herramientas que permiten reducir dichos riesgos y maximizar las oportunidades, entre otras:&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;ul style=&quot;margin-top:0cm&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom:0cm;margin-bottom:.0001pt;text-align:      justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;&lt;span style=&quot;mso-ansi-language:ES&quot; lang=&quot;ES&quot;&gt;Elaboración de planes de negocios &lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top:0cm&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom:0cm;margin-bottom:.0001pt;text-align:      justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;&lt;span style=&quot;mso-ansi-language:ES&quot; lang=&quot;ES&quot;&gt;Realización de estudios de factibilidad      (económico-financiera)&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;ul style=&quot;margin-top:0cm&quot; type=&quot;disc&quot;&gt;
&lt;li class=&quot;MsoNormal&quot; style=&quot;margin-bottom:0cm;margin-bottom:.0001pt;text-align:      justify;line-height:normal;mso-list:l0 level1 lfo1&quot;&gt;&lt;span style=&quot;mso-ansi-language:ES&quot; lang=&quot;ES&quot;&gt;Due&lt;span style=&quot;mso-spacerun:yes&quot;&gt; &lt;/span&gt;diligence&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;hr /&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Optimización y desarrollo de procesos de comercio exterior</title>
		<link rel="alternate" type="text/html" href="https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=54%3Aoptimizacion-y-desarrollo-de-procesos-de-comercio-exterior&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es"/>
		<published>2011-05-01T14:25:54Z</published>
		<updated>2011-05-01T14:25:54Z</updated>
		<id>https://cpaesmite.github.io/index.php?option=com_content&amp;view=article&amp;id=54%3Aoptimizacion-y-desarrollo-de-procesos-de-comercio-exterior&amp;catid=47%3Acategoria-de-servicios&amp;Itemid=55&amp;lang=es</id>
		<author>
			<name>Federico Esmite</name>
		<email>director@cpaesmite.com</email>
		</author>
		<summary type="html">&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Los procesos de comercio exterior involucran una gran cantidad de subprocesos&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;interrelacionados, todos ellos de vital importancia para la empresa. Una fuerte unión entre los distintos eslabones de la cadena logística, y especialmente el logro de relaciones sinérgicas entre los mismos es esencial.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: black;&quot; lang=&quot;ES-UY&quot;&gt;Brindamos a las empresas interesadas en iniciar, desarrollar, consolidar o mejorar sus procesos de comercio exterior, formas de trabajo óptimas y acordes a su realidad, como medio para lograr un incremento de su competitividad y rentabilidad. La consultoría en procesos de comercio exterior se centra en los siguientes servicios:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: black;&quot; lang=&quot;ES-UY&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 71.4pt; text-align: justify; text-indent: -18.0pt; mso-list: l2 level1 lfo4;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Análisis y optimización de procesos de comercio exterior&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 71.4pt; text-align: justify; text-indent: -18.0pt; mso-list: l2 level1 lfo4;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Apoyo en el desarrollo de nuevos negocios internacionales&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 71.4pt; text-align: justify; text-indent: -18.0pt; mso-list: l2 level1 lfo4;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;hr class=&quot;system-pagebreak&quot; /&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Análisis y optimización de procesos de comercio exterior&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Trabajamos sobre las distintas etapas que involucran dichos procesos, analizando su diseño, planificación, control, seguridad, tiempos y costos. A partir de dicho análisis se evalúan y plantean las distintas variables a mejorar, y de así ser requerido se proponen alternativas de cambio; pudiendo surgir desde simple acciones correctivas o preventivas, hasta la posible reingeniería de los procesos involucrados. También es parte del servicio brindado, la implementación de los cambios sugeridos y aprobados por la empresa, hasta el logro de los objetivos deseados. &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: black;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Apoyo en el desarrollo de nuevos negocios internacionales&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Apoyamos a la dirección de la&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;empresa en la implementación y desarrollo de nuevos negocios con el exterior, abordando entre otras las siguientes áreas y/o actividades:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Identificación y evaluación de alternativas logísticas vinculadas al comercio exterior (acuerdos internacionales, costos, tiempos, riesgos, etc.).&lt;/span&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Diseño e implementación de nuevos procesos: Importaciones, Exportaciones, Admisión temporaria,&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;Tránsito, Zona Franca, Puerto Libre, Depósitos aduaneros, etc.&lt;/span&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-fareast-font-family: &amp;quot;Times New Roman&amp;quot;; mso-bidi-font-family: Arial; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt;Análisis de exoneraciones objetivas y subjetivas, devolución de tributos, y demás beneficios vinculados al comercio exterior.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Estudios de factibilidad. &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Estudios de mercado a nivel nacional y regional.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Implementación de planes de exportación.&lt;/span&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Elaboración de agenda de negocios.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Asesoramiento en:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Contratos internacionales, &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Incoterms,&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Medios de pago, &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Transporte y seguros,&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Almacenaje y distribución.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l0 level1 lfo1;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Búsqueda de alternativas de financiación (BCU, Dinapyme, Proexport, etc.)&lt;/span&gt;&lt;span style=&quot;mso-fareast-font-family: &amp;quot;Times New Roman&amp;quot;; mso-bidi-font-family: Arial; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;</summary>
		<content type="html">&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Los procesos de comercio exterior involucran una gran cantidad de subprocesos&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;interrelacionados, todos ellos de vital importancia para la empresa. Una fuerte unión entre los distintos eslabones de la cadena logística, y especialmente el logro de relaciones sinérgicas entre los mismos es esencial.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: black;&quot; lang=&quot;ES-UY&quot;&gt;Brindamos a las empresas interesadas en iniciar, desarrollar, consolidar o mejorar sus procesos de comercio exterior, formas de trabajo óptimas y acordes a su realidad, como medio para lograr un incremento de su competitividad y rentabilidad. La consultoría en procesos de comercio exterior se centra en los siguientes servicios:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: black;&quot; lang=&quot;ES-UY&quot;&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 71.4pt; text-align: justify; text-indent: -18.0pt; mso-list: l2 level1 lfo4;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Análisis y optimización de procesos de comercio exterior&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 71.4pt; text-align: justify; text-indent: -18.0pt; mso-list: l2 level1 lfo4;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Apoyo en el desarrollo de nuevos negocios internacionales&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 71.4pt; text-align: justify; text-indent: -18.0pt; mso-list: l2 level1 lfo4;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;hr class=&quot;system-pagebreak&quot; /&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Análisis y optimización de procesos de comercio exterior&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Trabajamos sobre las distintas etapas que involucran dichos procesos, analizando su diseño, planificación, control, seguridad, tiempos y costos. A partir de dicho análisis se evalúan y plantean las distintas variables a mejorar, y de así ser requerido se proponen alternativas de cambio; pudiendo surgir desde simple acciones correctivas o preventivas, hasta la posible reingeniería de los procesos involucrados. También es parte del servicio brindado, la implementación de los cambios sugeridos y aprobados por la empresa, hasta el logro de los objetivos deseados. &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;color: black;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Apoyo en el desarrollo de nuevos negocios internacionales&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Apoyamos a la dirección de la&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;empresa en la implementación y desarrollo de nuevos negocios con el exterior, abordando entre otras las siguientes áreas y/o actividades:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;text-align: justify;&quot;&gt;&lt;strong style=&quot;mso-bidi-font-weight: normal;&quot;&gt;&lt;span lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Identificación y evaluación de alternativas logísticas vinculadas al comercio exterior (acuerdos internacionales, costos, tiempos, riesgos, etc.).&lt;/span&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Diseño e implementación de nuevos procesos: Importaciones, Exportaciones, Admisión temporaria,&lt;span style=&quot;mso-spacerun: yes;&quot;&gt; &lt;/span&gt;Tránsito, Zona Franca, Puerto Libre, Depósitos aduaneros, etc.&lt;/span&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-fareast-font-family: &amp;quot;Times New Roman&amp;quot;; mso-bidi-font-family: Arial; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt;Análisis de exoneraciones objetivas y subjetivas, devolución de tributos, y demás beneficios vinculados al comercio exterior.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Estudios de factibilidad. &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Estudios de mercado a nivel nacional y regional.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span lang=&quot;ES-UY&quot;&gt;Implementación de planes de exportación.&lt;/span&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Elaboración de agenda de negocios.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l3 level1 lfo2;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Asesoramiento en:&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Contratos internacionales, &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Incoterms,&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Medios de pago, &lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Transporte y seguros,&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 72.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l1 level2 lfo3;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Wingdings; mso-fareast-font-family: Wingdings; mso-bidi-font-family: Wingdings;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;§&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Almacenaje y distribución.&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;MsoNoSpacing&quot; style=&quot;margin-left: 36.0pt; text-align: justify; text-indent: -18.0pt; mso-list: l0 level1 lfo1;&quot;&gt;&lt;!--[if !supportLists]--&gt;&lt;span style=&quot;font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt;&lt;span style=&quot;mso-list: Ignore;&quot;&gt;·&lt;span style=&quot;font: 7.0pt &amp;quot;Times New Roman&amp;quot;;&quot;&gt; &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;!--[endif]--&gt;&lt;span style=&quot;mso-bidi-font-family: Tahoma;&quot; lang=&quot;ES-UY&quot;&gt;Búsqueda de alternativas de financiación (BCU, Dinapyme, Proexport, etc.)&lt;/span&gt;&lt;span style=&quot;mso-fareast-font-family: &amp;quot;Times New Roman&amp;quot;; mso-bidi-font-family: Arial; mso-fareast-language: ES-UY;&quot; lang=&quot;ES-UY&quot;&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;</content>
	</entry>
</feed>
